---
abstract: 'DBIx::Class Validation based on the column meta data'
author:
  - 'Sean Zellmer <sean@lejeunerenard.com>'
build_requires:
  Test::DBIx::Class: '0'
  Test::More: '0.88'
  Test::Warnings: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Validation-Structure
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  DBIx::Class: '0'
  Email::Valid: '0'
  HTML::TagFilter: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/lejeunerenard/DBIx-Class-Validation-Structure/issues
  homepage: https://github.com/lejeunerenard/DBIx-Class-Validation-Structure
  repository: https://github.com/lejeunerenard/DBIx-Class-Validation-Structure.git
version: '0.10'
